### ISSUE TITLE
Mismatch between reading mnemonic and required answer for kanji

### ISSUE THREAD

**Issue by tmr232** [jerryhcooke/smouldering_durtles#103]
First, I wan to say that this app is amazing, and has made my learning experience so much better! Thank you so much for your work!

As for my issue - since a few days ago, I started seeing cases in my reviews when the reading mnemonic did not match the reading the question required.

![Untitled](https://github.com/user-attachments/assets/013a60cd-843b-4c24-9c05-f026a93aefc3)

Here, for example, the answer is the on'yomi reading おう but the mnemonic is for the kun'yomi reading よこ.
Besides being very confusing, it does not align with what the lesson originally was, leading to mistakes.

I am currently running version 1.1.8 on Android 14.

**Comment by jerryhcooke** [comment]
Earlier this week there was an issue with the WaniKani API. I notified them about this and they have since fixed it, but if your app last pulled the data down before that fix, you may still have the old data. 

Update 1.1.5 was released to include a menu option that will allow single items to be synced manually if they have an issue., however I'd recommend going into settings and using the 'Reset database' option as this will pull ALL subject data fresh.

Just as note, I’d recommend always checking the thread of the community forums before reaching out by email, as you’ll typically find an issue like this has been covered already: https://community.wanikani.com/t/android-smouldering-durtles-v114-native-app-with-offline-lessons-and-reviews-plus-themes-and-script-like-features/61776

**Comment by tmr232** [comment]
Thanks!

And I'll try to check there first next time. I guess my developer-brain went "project on github ==> submit bug report"
