### ISSUE TITLE
Kanji Reading difference between website and app.

### ISSUE THREAD

**Issue by otacon6530** [jerryhcooke/smouldering_durtles#112]
Ok, I think SD may be either more picky or selecting the wrong reading to test against for these specific examples:

Hand, Wanikani accepts Te, SD only accepts Shuu

Dog, Wanikani accepts Inu, SD only accepts Ken.

Ball, Wanikani accepts Tama, SD only accepts Gyoku.

Not sure if this is a bug, a misunderstanding on my part or an intentional difference in the two testing mediums.

It was very confusing, since the lesson has a story for Tama and doesnt even mention Gyoku.

**Comment by jerryhcooke** [comment]
Earlier this week there was an issue with the WaniKani API. I notified them about this and they have since fixed it, but if your app last pulled the data down before that fix, you may still have the old data.

Update 1.1.5 was released to include a menu option that will allow single items to be synced manually if they have an issue., however I'd recommend going into settings and using the 'Reset database' option as this will pull ALL subject data fresh.

Just as note, I’d recommend always checking the [thread of the community forums ](https://community.wanikani.com/t/android-smouldering-durtles-v114-native-app-with-offline-lessons-and-reviews-plus-themes-and-script-like-features/61776)before reaching out by email, as you’ll typically find an issue like this has been covered already (and there's actually already been one issue that I've closed on here related to it as well 😅
