### ISSUE TITLE
discrepency between the app and the website

### ISSUE THREAD

**Issue by JimJoyyy** [jerryhcooke/smouldering_durtles#34]
While the website only warns you when mixing up the vocabulary/kanji, the app fails you. noticed it happening only on vocabulary as in other cases the app field shakes as expected.

![image](https://github.com/jerryhcooke/smouldering_durtles/assets/100526962/f5c0122f-733d-4fa2-a45b-432074f73727)
![image](https://github.com/jerryhcooke/smouldering_durtles/assets/100526962/679022fe-de54-4463-b7ac-b33d7a4456fa)

Just started using it, so if it is a setting i somehow messed up please just call me stupid and close it, but i have not changed any advanced things that were supposed to change behavior .-.

**Comment by jerryhcooke** [comment]
I'll take a look at this, because it shouldn't be the case (as I understand it) since the acceptable 'warn' items are pulled in with the other item info.

**Comment by jerryhcooke** [comment]
Looking into this, you probably haven't got the setting turned on to warn on a kanji reading being entered.

You're failing because とう isn't an accepted alternate reading for the vocab item:

    "readings": [
      {
        "primary": true,
        "reading": "かたな",
        "accepted_answer": true
      }
    ]
    
Go to Settings > Other advanced settings > Turn on 'Soft-reject on single-kanji vocabulary' and it'll shake and warn on the entry of the kanji reading for a single-kanji vocab item.

**Comment by shocklateboy92** [comment]
@jerryhcooke we should definitely enable that setting by default. Especially since it's hidden behind the "advanced settings might impede your learning" warning which scares most users away. We should match the website behavior by default.

**Comment by jerryhcooke** [comment]
Very fair point, will merge that change into the next build 👍🏼
