### ISSUE TITLE
Spikes Radical

### ISSUE THREAD

**Issue by Avery17** [jerryhcooke/smouldering_durtles#94]
Hello,

The spikes radical was recently updated on WaniKani and it is mismatched with the one in the app.

It really had me questioning reality. Here is a link to the update thread.

[https://community.wanikani.com/t/some-radical-character-images-replaced/66890](https://community.wanikani.com/t/some-radical-character-images-replaced/66890)

Thanks

**Comment by jerryhcooke** [comment]
Hi, 

For radicals that required images because there were not previously unicode characters, there's a bit of logical that replaces the title with an drawable vector xml. I've changed this logic to not replace the dozen radicals that now have unicode and removed the associated drawable files. 

All the best, 

Jerry
