### ISSUE TITLE
Some kanji reviews ask for wrong on'yomi/kun'yomi than website

### ISSUE THREAD

**Issue by Hegemege** [jerryhcooke/smouldering_durtles#96]
The app showed a shake warning when I entered the kun'yomi お for kanji 起 in a review session, and showed the on'yomi き as correct answer after giving up. The mnemonic teaches the kun'yomi however, and reviewing on website it works fine.

I think I had the same issue on the kanji 親 too - app asked for the reading that wasn't taught in the lesson for the kanji.

**Comment by jerryhcooke** [comment]
This is an issue with the WaniKani API that is currently being discussed in a few other apps threads.

Loosely, the issue comes from the API returning incorrect reading values when the batch size is larger than one subject, which is almost always.

There’s no way to engineer the app around this elegantly, so I’m afraid we need to wait for Tofugu to fix it.

**Comment by ParthKolekar** [comment]
Thanks for the comment.

**Comment by jerryhcooke** [comment]
A workaround for this has been introduced in the new build. 

If you encounter an item like this, use the menu in the top right and select 'Sync this subject' to get it corrected. 

Unfortunately this only works on an item-by-item basis, hopefully Tofugu will fix their API issue soon.
